apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "api-redis-chart.fullname" . }}-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "api-redis-chart.name" . }}-redis
  template:
    metadata:
      labels:
        app: {{ include "api-redis-chart.name" . }}-redis
    spec:
      containers:
        - name: redis
          image: "{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}"
          imagePullPolicy: {{ .Values.redis.image.pullPolicy }}
          ports:
            - containerPort: 6379
